name: Deploy SvelteKit Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
            cd /mnt/hdd/Skill-Forge
            git pull origin main
            pnpm install  # or npm/yarn
            pnpm build
            pm2 restart 5
